[package]
name = "wsbrd_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "wsbrd_cli"
path = "wsbrd_cli.rs"

[dependencies]
dbus = "0.9"
clap = { version = "3.0", features = ["derive"] }
